---

- name: Initialize
  deploy_helper: "path={{ project_root }} state=present"

- name: Clone project files
  git: "repo={{ project_git_repo }} dest={{ project_source_path }} version={{ project_version }}"
  when: project_deploy_strategy == 'git'

- name: Rsync project files
  synchronize: "src={{ project_local_path }} dest={{ project_source_path }} rsync_timeout={{ project_deploy_synchronize_timeout }} delete={{ project_deploy_synchronize_delete }} recursive=yes "
  when: project_deploy_strategy == 'synchronize'

- name: write unfinished file
  file: "path={{ project_source_path }}/{{ deploy_helper.unfinished_filename }} state=touch"

- name: Copy files to new build dir
  command: "cp -pr {{ project_source_path }} {{ deploy_helper.new_release_path }}"

- name: Remove unwanted files/folders from new release
  file: "path={{ deploy_helper.new_release_path }}/{{ item }} state=absent"
  with_items: project_unwanted_items

- name: Copy project files
  copy: src={{ item.src }} dest={{ deploy_helper.new_release_path }}/{{ item.dest }} mode={{ item.mode|default('0644') }}
  with_items: project_files

- name: Copy project templates
  template: src={{ item.src }} dest={{ deploy_helper.new_release_path }}/{{ item.dest }} mode={{ item.mode|default('0644') }}
  with_items: project_templates

- name: Run pre_build_commands in the new_release_path
  command: "{{ item }} chdir={{ deploy_helper.new_release_path }}"
  with_items: project_pre_build_commands
  environment: project_environment

- name: Do composer install
  command: "{{ project_command_for_composer_install }} chdir={{ deploy_helper.new_release_path }}"
  environment: project_environment
  when: project_has_composer

- name: Do npm install
  command: "{{ project_command_for_npm_install }} chdir={{ deploy_helper.new_release_path }}"
  environment: project_environment
  when: project_has_npm

- name: Do bower install
  command: "{{ project_command_for_bower_install }} chdir={{ deploy_helper.new_release_path }}"
  environment: project_environment
  when: project_has_bower

- name: Ensure shared sources are present
  file: "path='{{ deploy_helper.shared_path }}/{{ item.src }}' state={{ item.type|default('directory') }}"
  with_items: project_shared_children

- name: Ensure shared paths are absent
  file: "path='{{ deploy_helper.new_release_path }}/{{ item.path }}' state=absent"
  with_items: project_shared_children

- name: Create shared symlinks
  file: "path='{{ deploy_helper.new_release_path }}/{{ item.path }}' src='{{ deploy_helper.shared_path }}/{{ item.src }}' state=link"
  with_items: project_shared_children

- name: Run post_build_commands in the new_release_path
  command: "{{ item }} chdir={{ deploy_helper.new_release_path }}"
  with_items: project_post_build_commands
  environment: project_environment

- name: Finalize the deploy
  deploy_helper: path={{ project_root }} release={{ deploy_helper.new_release }} state=finalize
  when: project_finalize
